version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: soa-postgres
    environment:
      POSTGRES_DB: soa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: